'use client';

import { FormEvent, useState } from 'react';

type Requirement = { requirement:string; priority:'required'|'preferred'; status:'matched'|'partial'|'missing'; evidence:string };
type Result = { match_score:number; score_breakdown:{technical_skills:number;experience_projects:number;education_domain:number;other_requirements:number}; detected_language:string; summary:string; requirements:Requirement[]; matched_skills:string[]; missing_skills:string[]; keywords:string[]; analysis_seconds:number };
type Writing = { cv_suggestions:string[]; cover_letter:string; interview_questions:string[]; generation_seconds:number };

function Chips({items,tone='good'}:{items:string[];tone?:'good'|'warn'|'neutral'}){return <div className="chips">{items.map((x,i)=><span className={`chip ${tone}`} key={`${tone}-${i}-${x}`}>{x}</span>)}</div>}
function Status({value}:{value:Requirement['status']}){return <span className={`status ${value}`}>{value}</span>}

export default function Home(){
 const [cv,setCv]=useState<File|null>(null),[job,setJob]=useState(''),[result,setResult]=useState<Result|null>(null),[writing,setWriting]=useState<Writing|null>(null);
 const [loading,setLoading]=useState(false),[generating,setGenerating]=useState(false),[error,setError]=useState('');
 const api=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
 async function submit(e:FormEvent){e.preventDefault();if(!cv)return setError('Please select your CV as a PDF.');setLoading(true);setError('');setResult(null);setWriting(null);const d=new FormData();d.append('cv',cv);d.append('job_description',job);try{const r=await fetch(`${api}/analyze`,{method:'POST',body:d});const b=await r.json();if(!r.ok)throw new Error(b.detail||'Analysis failed.');setResult(b)}catch(e){setError(e instanceof Error?e.message:'Analysis failed.')}finally{setLoading(false)}}
 async function generate(){if(!cv||!result)return;setGenerating(true);setError('');const d=new FormData();d.append('cv',cv);d.append('job_description',job);d.append('analysis_json',JSON.stringify(result));try{const r=await fetch(`${api}/generate`,{method:'POST',body:d});const b=await r.json();if(!r.ok)throw new Error(b.detail||'Generation failed.');setWriting(b)}catch(e){setError(e instanceof Error?e.message:'Generation failed.')}finally{setGenerating(false)}}
 return <main>
  <nav className="topbar"><div className="brand"><span className="brandMark">MA</span><span>AI Job Application Assistant</span></div><div className="navMeta"><span>v1.6.1</span><span className="onlineDot"/>Local-first</div></nav>
  <section className="hero"><div className="badge">EVIDENCE-BASED • LOCAL AI • PRIVACY-FIRST</div><h1>Match your CV to a job.<br/><span>Without inventing experience.</span></h1><p>Transparent requirement matching and deterministic scoring first. Guarded local-AI writing only when you need it.</p><div className="heroStats"><div><b>100</b><span>point transparent score</span></div><div><b>3</b><span>evidence states</span></div><div><b>Local</b><span>Ollama inference</span></div></div></section>
  <section className="workspace"><div className="sectionHead"><div><span className="eyebrow">01 • ANALYZE</span><h2>Compare CV & role</h2></div><p>Your documents stay on the machine running the backend.</p></div>
  <form className="inputGrid" onSubmit={submit}><label className="card upload"><strong>Upload your CV</strong><span>Text-readable PDF • max 5 MB</span><input type="file" accept="application/pdf,.pdf" onChange={e=>setCv(e.target.files?.[0]||null)}/><div className={`fileBox ${cv?'selected':''}`}><span className="uploadIcon">↑</span><b>{cv?cv.name:'Choose PDF CV'}</b><small>{cv?'Ready for evidence analysis':'Click to select your CV'}</small></div></label><label className="card"><strong>Paste the job description</strong><span>Use the complete responsibilities and requirements</span><textarea required minLength={80} value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste the complete job posting here…"/><small className="counter">{job.length.toLocaleString()} characters</small></label><button className="primary" disabled={loading}>{loading?<><span className="spinner"/>Analyzing evidence…</>:'Analyze Match →'}</button></form></section>
  {error&&<div className="error"><b>Request failed</b><span>{error}</span></div>}
  {result&&<section className="results">
   <div className="sectionHead"><div><span className="eyebrow">02 • EVIDENCE</span><h2>Application match</h2></div><span className="language">{result.detected_language} • {result.analysis_seconds}s analysis</span></div>
   <div className="scoreCard"><div className="score"><b>{result.match_score}</b><small>/100</small></div><div className="scoreCopy"><span className="eyebrow">EVIDENCE-BASED SCORE</span><h2>{result.match_score>=70?'Strong alignment':result.match_score>=45?'Promising alignment':'Partial alignment'}</h2><p>{result.summary}</p><small>The LLM does not control this score.</small></div></div>
   <article className="card"><div className="cardTitle"><h3>Why this score?</h3><span>Deterministic weighting</span></div><div className="breakdown"><div><b>{result.score_breakdown.technical_skills}<small>/45</small></b><span>Technical skills</span></div><div><b>{result.score_breakdown.experience_projects}<small>/25</small></b><span>Experience & projects</span></div><div><b>{result.score_breakdown.education_domain}<small>/15</small></b><span>Education & domain</span></div><div><b>{result.score_breakdown.other_requirements}<small>/15</small></b><span>Other requirements</span></div></div></article>
   <article className="card"><div className="cardTitle"><h3>Requirement Evidence</h3><span>{result.requirements.length} requirements analyzed</span></div><div className="requirements">{result.requirements.map((r,i)=><div className={`requirement ${r.status}`} key={`r-${i}`}><div className="requirementTop"><b>{r.requirement}</b><div><span className="priority">{r.priority}</span><Status value={r.status}/></div></div><small>{r.evidence}</small></div>)}</div></article>
   <div className="twoCol"><article className="card"><div className="cardTitle"><h3>Verified Matches</h3><span>{result.matched_skills.length}</span></div><Chips items={result.matched_skills}/></article><article className="card"><div className="cardTitle"><h3>Missing / Unverified</h3><span>{result.missing_skills.length}</span></div><Chips items={result.missing_skills} tone="warn"/></article></div>
   <article className="card"><div className="cardTitle"><h3>ATS Keywords</h3><span>Detected from the role</span></div><Chips items={result.keywords} tone="neutral"/></article>
   <div className="generatePanel"><div><span className="eyebrow">03 • GENERATE</span><h3>Turn evidence into application material</h3><p>Suggestions and interview questions remain evidence-based. The local model writes the cover letter behind generation guardrails.</p></div><button className="primary" onClick={generate} disabled={generating} type="button">{generating?<><span className="spinner"/>Generating locally…</>:'Generate Application Materials →'}</button></div>
   {writing&&<section className="writing"><div className="sectionHead"><div><span className="eyebrow">04 • PREPARE</span><h2>Application materials</h2></div><span className="language">Local AI • {writing.generation_seconds}s</span></div><div className="twoCol writingTop"><article className="card"><div className="cardTitle"><h3>CV Improvement Suggestions</h3><span>3 evidence-aware actions</span></div><ol>{writing.cv_suggestions.map((x,i)=><li key={`s-${i}`}>{x}</li>)}</ol></article><article className="card"><div className="cardTitle"><h3>Interview Questions</h3><span>5 role-specific prompts</span></div><ol>{writing.interview_questions.map((x,i)=><li key={`q-${i}`}>{x}</li>)}</ol></article></div><article className="card cover"><div className="cardTitle"><h3>Tailored Cover Letter</h3><span>Guarded local generation</span></div><pre>{writing.cover_letter}</pre></article></section>}
  </section>}
  <footer><div><b>AI Job Application Assistant</b><span>Portfolio project by Mehrdad Afshari</span></div><div>Next.js • TypeScript • FastAPI • Python • Ollama</div></footer>
 </main>
}
